export const departmentList = [
  "Beleza",
  "Cuidados Pessoais",
  "Esportes e Aventura",
  "Vestuário",
  "Calçados",
  "Bijuterias e Acessórios",
  "Eletrodomésticos",
  "Celulares, Tablets e Acessórios",
  "Câmeras e Acessórios",
  "Casa, Jardim e Limpeza",
  "Móveis e Decoração",
  "Construção",
  "Tempor",
  "Consequat",
  "Sit Amet",
  "Consequat",
  "Pellentesque",
  "Petshop",
  "Produtos Regionais",
  "Brinquedos e Jogos",
  "Livros",
  "Música e Hobbies",
  "Bebês",
  "Alimentos e Bebidas",
  "Agro e Indústria"
];
